import {defineArrayMember, defineField, defineType} from 'sanity'
import {seoFields} from './objects'

export const documentTypes = [
  defineType({
    name: 'siteSettings',
    title: 'Site Settings',
    type: 'document',
    fields: [
      defineField({name: 'title', type: 'string', initialValue: 'Velaris Web'}),
      defineField({name: 'siteUrl', title: 'Site URL', type: 'url'}),
      defineField({name: 'logo', type: 'imageWithAlt'}),
      defineField({name: 'icon', type: 'imageWithAlt'}),
      defineField({name: 'description', type: 'text', rows: 3}),
      defineField({name: 'primaryCta', type: 'cta'}),
      defineField({name: 'socialLinks', type: 'array', of: [defineArrayMember({type: 'link'})]}),
      defineField({name: 'footerText', type: 'text', rows: 3}),
      defineField({name: 'defaultSeo', type: 'object', fields: seoFields}),
    ],
    preview: {
      prepare() {
        return {title: 'Site Settings'}
      },
    },
  }),
  defineType({
    name: 'navigation',
    title: 'Navigation',
    type: 'document',
    fields: [
      defineField({name: 'title', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'location', type: 'string', options: {list: ['header', 'footer', 'utility']}}),
      defineField({name: 'items', type: 'array', of: [defineArrayMember({type: 'link'})]}),
    ],
  }),
  defineType({
    name: 'page',
    title: 'Pages',
    type: 'document',
    fields: [
      defineField({name: 'title', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'slug', type: 'slug', options: {source: 'title'}, validation: (Rule) => Rule.required()}),
      defineField({
        name: 'pageType',
        type: 'string',
        options: {
          list: ['home', 'about', 'services', 'case-studies', 'resources', 'blog', 'pricing', 'playbook', 'legal', 'landing'],
        },
      }),
      defineField({name: 'intro', type: 'text', rows: 3}),
      defineField({name: 'sections', type: 'array', of: [defineArrayMember({type: 'pageSection'})]}),
      defineField({name: 'seo', type: 'object', fields: seoFields}),
    ],
  }),
  defineType({
    name: 'service',
    title: 'Services',
    type: 'document',
    fields: [
      defineField({name: 'name', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'slug', type: 'slug', options: {source: 'name'}, validation: (Rule) => Rule.required()}),
      defineField({name: 'orderRank', title: 'Sort order', type: 'number'}),
      defineField({name: 'tag', type: 'string'}),
      defineField({name: 'icon', type: 'string'}),
      defineField({name: 'featured', type: 'boolean', initialValue: false}),
      defineField({name: 'shortDescription', type: 'text', rows: 3}),
      defineField({name: 'tagline', type: 'string'}),
      defineField({name: 'intro', type: 'text', rows: 5}),
      defineField({name: 'heroImage', type: 'imageWithAlt'}),
      defineField({name: 'heroImagePath', title: 'Legacy hero image path', type: 'string'}),
      defineField({name: 'features', type: 'array', of: [defineArrayMember({type: 'string'})]}),
      defineField({name: 'includes', type: 'array', of: [defineArrayMember({type: 'string'})]}),
      defineField({name: 'benefits', type: 'array', of: [defineArrayMember({type: 'processStep'})]}),
      defineField({name: 'process', type: 'array', of: [defineArrayMember({type: 'processStep'})]}),
      defineField({
        name: 'capabilities',
        type: 'array',
        of: [
          defineArrayMember({
            type: 'object',
            fields: [
              defineField({name: 'title', type: 'string'}),
              defineField({name: 'description', type: 'text', rows: 2}),
            ],
          }),
        ],
      }),
      defineField({name: 'highlights', type: 'array', of: [defineArrayMember({type: 'stat'})]}),
      defineField({name: 'bestFor', type: 'text', rows: 2}),
      defineField({name: 'deliverable', type: 'text', rows: 2}),
      defineField({name: 'startingPrice', type: 'string'}),
      defineField({name: 'body', type: 'portableBody'}),
      defineField({name: 'seo', type: 'object', fields: seoFields}),
    ],
  }),
  defineType({
    name: 'caseStudy',
    title: 'Case Studies',
    type: 'document',
    fields: [
      defineField({name: 'client', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'slug', type: 'slug', options: {source: 'client'}, validation: (Rule) => Rule.required()}),
      defineField({name: 'caseNumber', type: 'string'}),
      defineField({name: 'sector', type: 'string'}),
      defineField({name: 'industry', type: 'string'}),
      defineField({name: 'projectClient', title: 'Contact/client person', type: 'string'}),
      defineField({name: 'headline', type: 'string'}),
      defineField({name: 'summary', type: 'text', rows: 4}),
      defineField({name: 'challenge', type: 'text', rows: 4}),
      defineField({name: 'approach', type: 'text', rows: 5}),
      defineField({name: 'outcome', type: 'text', rows: 4}),
      defineField({name: 'liveUrl', type: 'url'}),
      defineField({name: 'featured', type: 'boolean', initialValue: false}),
      defineField({name: 'darkTheme', type: 'boolean', initialValue: false}),
      defineField({name: 'logo', type: 'imageWithAlt'}),
      defineField({name: 'logoPath', title: 'Legacy logo path', type: 'string'}),
      defineField({name: 'heroImage', type: 'imageWithAlt'}),
      defineField({name: 'heroImagePath', title: 'Legacy hero image path', type: 'string'}),
      defineField({name: 'gallery', type: 'array', of: [defineArrayMember({type: 'imageWithAlt'})]}),
      defineField({name: 'galleryPaths', title: 'Legacy gallery paths', type: 'array', of: [defineArrayMember({type: 'string'})]}),
      defineField({name: 'pageScreenshots', type: 'array', of: [defineArrayMember({type: 'pageScreenshot'})]}),
      defineField({name: 'services', type: 'array', of: [defineArrayMember({type: 'string'})]}),
      defineField({name: 'deliverables', type: 'array', of: [defineArrayMember({type: 'string'})]}),
      defineField({name: 'timeline', type: 'string'}),
      defineField({name: 'results', type: 'array', of: [defineArrayMember({type: 'stat'})]}),
      defineField({name: 'quote', type: 'text', rows: 5}),
      defineField({name: 'quoteAuthor', type: 'string'}),
      defineField({name: 'quoteRole', type: 'string'}),
      defineField({name: 'quoteAvatar', type: 'imageWithAlt'}),
      defineField({name: 'quoteAvatarPath', title: 'Legacy quote avatar path', type: 'string'}),
      defineField({name: 'fonts', type: 'object', fields: [
        defineField({name: 'display', type: 'string'}),
        defineField({name: 'ui', type: 'string'}),
        defineField({name: 'displayStack', type: 'string'}),
        defineField({name: 'uiStack', type: 'string'}),
      ]}),
      defineField({name: 'palette', type: 'array', of: [defineArrayMember({type: 'paletteColor'})]}),
      defineField({name: 'targetKeywords', type: 'array', of: [defineArrayMember({type: 'string'})], options: {layout: 'tags'}}),
      defineField({name: 'body', type: 'portableBody'}),
      defineField({name: 'seo', type: 'object', fields: seoFields}),
    ],
  }),
  defineType({
    name: 'post',
    title: 'Blog Posts',
    type: 'document',
    fields: [
      defineField({name: 'title', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'slug', type: 'slug', options: {source: 'title'}, validation: (Rule) => Rule.required()}),
      defineField({name: 'category', type: 'reference', to: [{type: 'category'}]}),
      defineField({name: 'categoryName', title: 'Legacy category name', type: 'string'}),
      defineField({name: 'targetKeyword', type: 'string'}),
      defineField({name: 'excerpt', type: 'text', rows: 3, validation: (Rule) => Rule.max(220)}),
      defineField({name: 'coverImage', type: 'imageWithAlt'}),
      defineField({name: 'coverGraphicKey', type: 'string'}),
      defineField({name: 'author', type: 'reference', to: [{type: 'author'}]}),
      defineField({name: 'authorName', title: 'Legacy author name', type: 'string', initialValue: 'Deluar Ahamed'}),
      defineField({name: 'publishedAt', type: 'datetime'}),
      defineField({name: 'readTimeMinutes', type: 'number'}),
      defineField({name: 'body', type: 'portableBody'}),
      defineField({name: 'legacyHtmlBody', title: 'Legacy HTML body', type: 'text', rows: 12}),
      defineField({name: 'relatedServices', type: 'array', of: [defineArrayMember({type: 'reference', to: [{type: 'service'}]})]}),
      defineField({name: 'relatedCaseStudies', type: 'array', of: [defineArrayMember({type: 'reference', to: [{type: 'caseStudy'}]})]}),
      defineField({name: 'seo', type: 'object', fields: seoFields}),
    ],
  }),
  defineType({
    name: 'category',
    title: 'Categories',
    type: 'document',
    fields: [
      defineField({name: 'title', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'slug', type: 'slug', options: {source: 'title'}, validation: (Rule) => Rule.required()}),
      defineField({name: 'description', type: 'text', rows: 3}),
      defineField({name: 'color', type: 'string'}),
    ],
  }),
  defineType({
    name: 'author',
    title: 'Authors',
    type: 'document',
    fields: [
      defineField({name: 'name', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'slug', type: 'slug', options: {source: 'name'}, validation: (Rule) => Rule.required()}),
      defineField({name: 'role', type: 'string'}),
      defineField({name: 'avatar', type: 'imageWithAlt'}),
      defineField({name: 'bio', type: 'text', rows: 4}),
      defineField({name: 'linkedinUrl', type: 'url'}),
    ],
  }),
  defineType({
    name: 'resource',
    title: 'Resources',
    type: 'document',
    fields: [
      defineField({name: 'title', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'slug', type: 'slug', options: {source: 'title'}, validation: (Rule) => Rule.required()}),
      defineField({name: 'resourceType', type: 'string', options: {list: ['playbook', 'e-book', 'checklist', 'template', 'guide', 'video', 'webinar', 'mini-course', 'notion-kit']}}),
      defineField({name: 'category', type: 'string'}),
      defineField({name: 'price', type: 'string'}),
      defineField({name: 'description', type: 'text', rows: 4}),
      defineField({name: 'coverImage', type: 'imageWithAlt'}),
      defineField({name: 'coverImagePath', title: 'Legacy cover image path', type: 'string'}),
      defineField({name: 'file', type: 'file'}),
      defineField({name: 'ctaLabel', type: 'string'}),
      defineField({name: 'featured', type: 'boolean', initialValue: false}),
      defineField({name: 'body', type: 'portableBody'}),
      defineField({name: 'seo', type: 'object', fields: seoFields}),
    ],
  }),
  defineType({
    name: 'leadMagnet',
    title: 'Lead Magnets',
    type: 'document',
    fields: [
      defineField({name: 'title', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'slug', type: 'slug', options: {source: 'title'}, validation: (Rule) => Rule.required()}),
      defineField({name: 'description', type: 'text', rows: 4}),
      defineField({name: 'coverImage', type: 'imageWithAlt'}),
      defineField({name: 'pdf', type: 'file'}),
      defineField({name: 'audience', type: 'array', of: [defineArrayMember({type: 'string'})]}),
      defineField({name: 'chapters', type: 'array', of: [defineArrayMember({type: 'processStep'})]}),
      defineField({name: 'formFields', type: 'array', of: [defineArrayMember({type: 'string'})]}),
      defineField({name: 'successMessage', type: 'text', rows: 2}),
      defineField({name: 'body', type: 'portableBody'}),
      defineField({name: 'seo', type: 'object', fields: seoFields}),
    ],
  }),
  defineType({
    name: 'testimonial',
    title: 'Testimonials',
    type: 'document',
    fields: [
      defineField({name: 'name', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'role', type: 'string'}),
      defineField({name: 'company', type: 'string'}),
      defineField({name: 'quote', type: 'text', rows: 5, validation: (Rule) => Rule.required()}),
      defineField({name: 'stars', type: 'number', initialValue: 5}),
      defineField({name: 'avatar', type: 'imageWithAlt'}),
      defineField({name: 'avatarPath', title: 'Legacy avatar path', type: 'string'}),
      defineField({name: 'companyLogo', type: 'imageWithAlt'}),
      defineField({name: 'caseStudy', type: 'reference', to: [{type: 'caseStudy'}]}),
      defineField({name: 'featured', type: 'boolean', initialValue: false}),
    ],
  }),
  defineType({
    name: 'clientLogo',
    title: 'Client Logos',
    type: 'document',
    fields: [
      defineField({name: 'name', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'logo', type: 'imageWithAlt'}),
      defineField({name: 'logoPath', title: 'Legacy logo path', type: 'string'}),
      defineField({name: 'website', type: 'url'}),
      defineField({name: 'caseStudy', type: 'reference', to: [{type: 'caseStudy'}]}),
    ],
  }),
  defineType({
    name: 'pricingPlan',
    title: 'Pricing Plans',
    type: 'document',
    fields: [
      defineField({name: 'name', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'price', type: 'string'}),
      defineField({name: 'period', type: 'string'}),
      defineField({name: 'tagline', type: 'text', rows: 2}),
      defineField({name: 'features', type: 'array', of: [defineArrayMember({type: 'string'})]}),
      defineField({name: 'cta', type: 'cta'}),
      defineField({name: 'featured', type: 'boolean', initialValue: false}),
      defineField({name: 'orderRank', title: 'Sort order', type: 'number'}),
    ],
  }),
  defineType({
    name: 'faq',
    title: 'FAQs',
    type: 'document',
    fields: [
      defineField({name: 'question', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'answer', type: 'text', rows: 4, validation: (Rule) => Rule.required()}),
      defineField({name: 'category', type: 'string'}),
      defineField({name: 'orderRank', title: 'Sort order', type: 'number'}),
    ],
  }),
]
