import {defineField, defineType} from 'sanity'

const seoFields = [
  defineField({name: 'metaTitle', title: 'Meta title', type: 'string', validation: (Rule) => Rule.max(60)}),
  defineField({name: 'metaDescription', title: 'Meta description', type: 'text', rows: 3, validation: (Rule) => Rule.max(160)}),
  defineField({name: 'ogImage', title: 'Open Graph image', type: 'image', options: {hotspot: true}}),
  defineField({name: 'canonicalUrl', title: 'Canonical URL', type: 'url'}),
]

const portableBody = defineField({
  name: 'body',
  title: 'Body',
  type: 'array',
  of: [
    {type: 'block'},
    {type: 'image', options: {hotspot: true}},
    {
      type: 'object',
      name: 'callout',
      title: 'Callout',
      fields: [
        {name: 'tone', type: 'string', options: {list: ['teal', 'navy', 'cream', 'warning']}},
        {name: 'text', type: 'text', rows: 3},
      ],
    },
  ],
})

export const schemaTypes = [
  defineType({
    name: 'seoPage',
    title: 'SEO Pages',
    type: 'document',
    fields: [
      defineField({name: 'title', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'slug', type: 'slug', options: {source: 'title'}, validation: (Rule) => Rule.required()}),
      defineField({name: 'pageType', type: 'string', options: {list: ['home', 'service', 'case-study', 'blog', 'resource', 'pricing', 'about', 'playbook']}}),
      ...seoFields,
      defineField({name: 'schemaJson', title: 'Structured data JSON', type: 'text', rows: 8}),
    ],
  }),
  defineType({
    name: 'post',
    title: 'Blog Posts',
    type: 'document',
    fields: [
      defineField({name: 'title', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'slug', type: 'slug', options: {source: 'title'}, validation: (Rule) => Rule.required()}),
      defineField({name: 'category', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'excerpt', type: 'text', rows: 3, validation: (Rule) => Rule.required().max(220)}),
      defineField({name: 'coverImage', type: 'image', options: {hotspot: true}, validation: (Rule) => Rule.required()}),
      defineField({name: 'author', type: 'string', initialValue: 'Deluar Ahamed'}),
      defineField({name: 'publishedAt', type: 'datetime'}),
      defineField({name: 'readTime', type: 'string'}),
      defineField({name: 'keywords', type: 'array', of: [{type: 'string'}]}),
      portableBody,
      ...seoFields,
    ],
  }),
  defineType({
    name: 'resource',
    title: 'Resources',
    type: 'document',
    fields: [
      defineField({name: 'title', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'slug', type: 'slug', options: {source: 'title'}, validation: (Rule) => Rule.required()}),
      defineField({name: 'resourceType', type: 'string', options: {list: ['playbook', 'checklist', 'template', 'guide', 'video', 'webinar']}}),
      defineField({name: 'description', type: 'text', rows: 4}),
      defineField({name: 'coverImage', type: 'image', options: {hotspot: true}}),
      defineField({name: 'file', type: 'file'}),
      defineField({name: 'ctaLabel', type: 'string'}),
      defineField({name: 'featured', type: 'boolean', initialValue: false}),
      ...seoFields,
    ],
  }),
  defineType({
    name: 'caseStudy',
    title: 'Case Studies',
    type: 'document',
    fields: [
      defineField({name: 'client', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'slug', type: 'slug', options: {source: 'client'}, validation: (Rule) => Rule.required()}),
      defineField({name: 'industry', type: 'string'}),
      defineField({name: 'liveUrl', type: 'url'}),
      defineField({name: 'services', type: 'array', of: [{type: 'string'}]}),
      defineField({name: 'deliverables', type: 'array', of: [{type: 'string'}]}),
      defineField({name: 'timeline', type: 'string'}),
      defineField({name: 'summary', type: 'text', rows: 4}),
      defineField({name: 'logo', type: 'image'}),
      defineField({name: 'heroImage', type: 'image', options: {hotspot: true}}),
      defineField({name: 'screenshots', type: 'array', of: [{type: 'image', options: {hotspot: true}}]}),
      defineField({name: 'results', type: 'array', of: [{type: 'object', fields: [{name: 'value', type: 'string'}, {name: 'label', type: 'string'}]}]}),
      portableBody,
      ...seoFields,
    ],
  }),
  defineType({
    name: 'service',
    title: 'Services',
    type: 'document',
    fields: [
      defineField({name: 'name', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'slug', type: 'slug', options: {source: 'name'}, validation: (Rule) => Rule.required()}),
      defineField({name: 'shortDescription', type: 'text', rows: 3}),
      defineField({name: 'icon', type: 'string'}),
      defineField({name: 'heroImage', type: 'image', options: {hotspot: true}}),
      defineField({name: 'benefits', type: 'array', of: [{type: 'string'}]}),
      defineField({name: 'process', type: 'array', of: [{type: 'object', fields: [{name: 'title', type: 'string'}, {name: 'description', type: 'text'}]}]}),
      defineField({name: 'startingPrice', type: 'string'}),
      portableBody,
      ...seoFields,
    ],
  }),
  defineType({
    name: 'testimonial',
    title: 'Testimonials',
    type: 'document',
    fields: [
      defineField({name: 'name', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'role', type: 'string'}),
      defineField({name: 'company', type: 'string'}),
      defineField({name: 'quote', type: 'text', rows: 5, validation: (Rule) => Rule.required()}),
      defineField({name: 'avatar', type: 'image', options: {hotspot: true}}),
      defineField({name: 'companyLogo', type: 'image'}),
      defineField({name: 'caseStudy', type: 'reference', to: [{type: 'caseStudy'}]}),
      defineField({name: 'featured', type: 'boolean', initialValue: false}),
    ],
  }),
  defineType({
    name: 'clientLogo',
    title: 'Client Logos',
    type: 'document',
    fields: [
      defineField({name: 'name', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'logo', type: 'image', validation: (Rule) => Rule.required()}),
      defineField({name: 'website', type: 'url'}),
      defineField({name: 'caseStudy', type: 'reference', to: [{type: 'caseStudy'}]}),
    ],
  }),
  defineType({
    name: 'leadMagnet',
    title: 'Lead Magnets',
    type: 'document',
    fields: [
      defineField({name: 'title', type: 'string', validation: (Rule) => Rule.required()}),
      defineField({name: 'slug', type: 'slug', options: {source: 'title'}, validation: (Rule) => Rule.required()}),
      defineField({name: 'description', type: 'text', rows: 4}),
      defineField({name: 'coverImage', type: 'image', options: {hotspot: true}}),
      defineField({name: 'pdf', type: 'file'}),
      defineField({name: 'formFields', type: 'array', of: [{type: 'string'}]}),
      defineField({name: 'successMessage', type: 'text', rows: 2}),
      portableBody,
      ...seoFields,
    ],
  }),
]
